[package]
name = "kbdprof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.1"
sqlite = "0.27.0"
log = "0.4.17"
simplelog = "0.12.0"